server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    '[ru.spb.tksoft.aichains.project]': INFO
    '[org.springframework.web]': INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

spring:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

  main:
    banner-mode: console

  application:
    name: ai-chains-project

  output:
    ansi:
      enabled: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: false
