server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  # Don't touch Jackson configuration
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

  main:
    banner-mode: console
  application:
    name: ai-chains-project
  sql:
    init:
      mode: never
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: false

  # PostgreSQL configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ai_chains}
    username: ${DB_USER:ai_chains_god}
    password: ${DB_PASSWORD:87654321}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ai_chains}
    user: ${DB_USER:ai_chains_god}
    password: ${DB_PASSWORD:87654321}

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: false
# # Simplified logging configuration for non-production environments
# logging:
#   level:
#     '[ru.spb.tksoft.chains.project]': INFO
#     '[org.springframework.web]': INFO
#   pattern:
#     console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
