server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: ai-chains
  sql:
    init:
      mode: never
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ai_chains}
    username: ${DB_USER:ai_chains_god}
    password: ${DB_PASSWORD:87654321}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ai_chains}
    user: ${DB_USER:ai_chains_god}
    password: ${DB_PASSWORD:87654321}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
