# Конфигурация Spring Boot приложения

# Настройки сервера
server:
  port: 8080
  servlet:
    context-path: /

# Настройки логирования
logging:
  level:
    '[com.example.testjson]': INFO
    '[org.springframework.web]': INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

# Настройки JSON
spring:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  application:
    name: test-json
  main:
    banner-mode: console

# Настройки OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: false
