openapi: 3.0.0
info:
  title: Диаграммы REST API
  description: REST API для управления узлами, соединительными линиями и диаграммами.
  version: 1.0.0
servers:
  - url: https://example.com/api/v1
paths:
  "/templates":
    get:
      tags:
        - Diagrams
      summary: Получение списка диаграмм
      operationId: listDiagrams
      responses:
        "200":
          description: Успешно получено
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ListItem"
        default:
          description: Произошла ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  "/templates/create":
    post:
      tags:
        - Diagrams
      summary: Создание новой диаграммы
      operationId: createDiagram
      responses:
        "201":
          description: Диаграмма успешно создана
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateResponse"
        default:
          description: Произошла ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  "/templates/{diagram_id}/save":
    post:
      tags:
        - Diagrams
      summary: Сохранение диаграммы
      operationId: saveDiagram
      parameters:
        - name: diagram_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID диаграммы
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Diagram"
      responses:
        "200":
          description: Диаграмма успешно сохранена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SaveResponse"
        default:
          description: Произошла ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  "/templates/{diagram_id}/delete":
    delete:
      tags:
        - Diagrams
      summary: Удаление диаграммы
      operationId: deleteDiagram
      parameters:
        - name: diagram_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID диаграммы
      responses:
        "204":
          description: Диаграмма успешно удалена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteResponse"
        default:
          description: Произошла ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    Node:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор узла
        id_ai:
          type: integer
          format: int64
          description: Связанный идентификатор AI-сущности
        name:
          type: string
          description: Имя узла
        description:
          type: string
          description: Описание узла
        text_in:
          type: string
          description: Входной текст
        text_out:
          type: string
          description: Выходной текст
    Line:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор линии
        id_node_begin:
          type: integer
          format: int64
          description: ID начального узла
        id_node_end:
          type: integer
          format: int64
          description: ID конечного узла
        description:
          type: string
          description: Описание линии
    Diagram:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор диаграммы
        name:
          type: string
          description: Имя диаграммы
        description:
          type: string
          description: Описание диаграммы
        nodes:
          type: array
          items:
            $ref: "#/components/schemas/Node"
        lines:
          type: array
          items:
            $ref: "#/components/schemas/Line"
    ListItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID элемента списка
        name:
          type: string
          description: Отображаемое имя элемента
    CreateResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID вновь созданной диаграммы
    SaveResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID сохранённой диаграммы
        name:
          type: string
          description: Имя сохранённой диаграммы
    DeleteResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID удалённой диаграммы
        name:
          type: string
          description: Имя удалённой диаграммы
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: Код ошибки
        message:
          type: string
          description: Сообщение об ошибке
        details:
          type: string
          description: Дополнительные детали ошибки
